students_grade=[]
students_grade.append((1,'A'))
students_grade.append((4,'sid'))
students_grade.sort(reverse=True)
print('Yes')
print(students_grade)
students_grade.append((3,'sid'))
students_grade.sort(reverse=True)
students_grade.append((2,'AG'))
students_grade.sort(reverse=True)
print("priority wise sorted")
print(students_grade)
print("original queue")
while students_grade:
    print(students_grade.pop())
